si_core:
    resource: "@SICoreBundle/Resources/config/routing.yml"
    prefix:   /


si_users:
    resource: "@SIUsersBundle/Resources/config/routing.yml"
    prefix:   /users

login:
    path:   /login
    defaults:  { _controller: SIUsersBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"