<?php

namespace SI\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Invoice_ItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Invoice_ItemsRepository extends EntityRepository
{
}
