<?php

namespace SI\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvoicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoicesRepository extends EntityRepository
{
    public function getTotalInvoice(){
        $queryBuilder = $this
            ->createQueryBuilder('i')

        ;

        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();

        // On récupère les résultats à partir de la Query
        $results = $query->getResult();

        //var_dump($results); exit;

        // On retourne ces résultats
        return $results;
    }

}
