<?php

namespace SI\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Quotation_itemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Quotation_itemsRepository extends EntityRepository
{
}
