<?php

namespace SI\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReglementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReglementRepository extends EntityRepository
{
}
